In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
import numpy as np
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
import numpy as np
c = np.zeros((3,5))
print (c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
import numpy as np
d = np.random.random((3,3))
print (d)

[[0.48927418 0.1819968  0.34121464]
 [0.11240123 0.16685598 0.67974217]
 [0.82112486 0.83968253 0.0524272 ]]


In [11]:
import numpy as np
e = np.arange (0,30,5)
print (e)

[ 0  5 10 15 20 25]


In [3]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [4]:
import numpy as np
flat = arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [5]:
import numpy as np
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 4)
12
int64
2


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[10,20,30,40],[11,22,33,44]])
newtype=arr.astype('f')
print("\n converted array element:\n",newtype)
print("converted array type:",arr.dtype)
size=len(arr)
print("\n size of array:\n", size)


 converted array element:
 [[ 1.  2.  3.  4.]
 [10. 20. 30. 40.]
 [11. 22. 33. 44.]]
converted array type: int64

 size of array:
 3
